import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['es', 'en', 'ca', 'eu', 'gl', 'fr'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? esText = '',
    String? enText = '',
    String? caText = '',
    String? euText = '',
    String? glText = '',
    String? frText = '',
  }) =>
      [esText, enText, caText, euText, glText, frText][languageIndex] ?? '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    '2srrhv5q': {
      'es': 'Hola,',
      'ca': 'Hola,',
      'en': 'Hello,',
      'eu': 'Kaixo,',
      'fr': 'Bonjour,',
      'gl': 'Ola,',
    },
    's12r9vqp': {
      'es': 'Hoy es',
      'ca': 'Avui és',
      'en': 'Today is',
      'eu': 'gaur da',
      'fr': 'aujourd\'hui c\'est',
      'gl': 'hoxe é',
    },
    'foqnms41': {
      'es': 'Peso',
      'ca': 'Pes',
      'en': 'Weight',
      'eu': 'Pisua',
      'fr': 'Poids',
      'gl': 'Peso',
    },
    '7ni7ulrb': {
      'es': 'Agua',
      'ca': 'Aigua',
      'en': 'Water',
      'eu': 'Ura',
      'fr': 'Eau',
      'gl': 'Auga',
    },
    'eo1muxci': {
      'es': '%',
      'ca': '%',
      'en': '%',
      'eu': '%',
      'fr': '%',
      'gl': '%',
    },
    'rhlwq0pw': {
      'es': 'Suplementos',
      'ca': 'Suplements',
      'en': 'Supplements',
      'eu': 'Osagarriak',
      'fr': 'Suppléments',
      'gl': 'Suplementos',
    },
    'y5s4ib1v': {
      'es': 'Estado de ánimo',
      'ca': 'Estat d\'ànim',
      'en': 'Mood',
      'eu': 'aldarte',
      'fr': 'humeur',
      'gl': 'estado de ánimo',
    },
    'rh19wef1': {
      'es': 'Medidas',
      'ca': 'Mesures',
      'en': 'Measures',
      'eu': 'Neurriak',
      'fr': 'Mesures',
      'gl': 'Medidas',
    },
    'b2xpmto5': {
      'es': 'Alimentación',
      'ca': 'Alimentació',
      'en': 'Feeding',
      'eu': 'Elikadura',
      'fr': 'Alimentation',
      'gl': 'Alimentación',
    },
    'c1k8z51f': {
      'es': 'Ejercicio',
      'ca': 'Exercici',
      'en': 'Exercise',
      'eu': 'Ariketa',
      'fr': 'Exercice',
      'gl': 'Exercicio',
    },
    '0rih8k1v': {
      'es': 'Inicio',
      'ca': 'Inici',
      'en': 'Start',
      'eu': 'Hasi',
      'fr': 'Commencer',
      'gl': 'Comeza',
    },
  },
  // Water
  {
    '10uaw5p9': {
      'es':
          'Recuerda añadir la cantidad de vasos de agua a tomar por día, en tu perfil de usuario.',
      'ca':
          'Recordeu afegir la quantitat de gots d\'aigua a prendre per dia, al vostre perfil d\'usuari.',
      'en':
          'Remember to add the number of glasses of water to drink per day in your user profile.',
      'eu':
          'Gogoratu zure erabiltzaile profilean egunean edateko ur edalontzi kopurua gehitzea.',
      'fr':
          'Pensez à ajouter le nombre de verres d\'eau à boire par jour dans votre profil utilisateur.',
      'gl':
          'Lembra engadir o número de vasos de auga para beber ao día no teu perfil de usuario.',
    },
    'ak87qr9t': {
      'es': 'Vasos tomados',
      'ca': 'Gots presos',
      'en': 'Glasses taken',
      'eu': 'hartutako betaurrekoak',
      'fr': 'lunettes prises',
      'gl': 'gafas tomadas',
    },
    '626c7jz4': {
      'es': 'Vasos / Día',
      'ca': 'Gots / Dia',
      'en': 'Glasses/Day',
      'eu': 'Betaurrekoak / Eguna',
      'fr': 'Lunettes / Jour',
      'gl': 'Gafas / Día',
    },
    'n1psybwk': {
      'es': '%',
      'ca': '%',
      'en': '%',
      'eu': '%',
      'fr': '%',
      'gl': '%',
    },
    'f21z35zu': {
      'es': 'Agua',
      'ca': 'Aigua',
      'en': 'Water',
      'eu': 'Ura',
      'fr': 'Eau',
      'gl': 'Auga',
    },
    'qc1xg4f6': {
      'es': 'Agua',
      'ca': 'Aigua',
      'en': 'Water',
      'eu': 'Ura',
      'fr': 'Eau',
      'gl': 'Auga',
    },
  },
  // Loading
  {
    'w5pbk1qe': {
      'es': 'Cargando...',
      'ca': 'Carregant...',
      'en': 'Charging...',
      'eu': 'Kargatzen...',
      'fr': 'Chargement...',
      'gl': 'Cargando...',
    },
    'sc9me2uh': {
      'es': 'Loading',
      'ca': 'Loading',
      'en': 'Loading',
      'eu': 'Kargatzen',
      'fr': 'Chargement',
      'gl': 'Cargando',
    },
  },
  // Profile
  {
    '9bkzsoo3': {
      'es': 'Datos',
      'ca': 'Dades',
      'en': 'Data',
      'eu': 'Datuak',
      'fr': 'Données',
      'gl': 'Datos',
    },
    '4ipj9hvp': {
      'es': 'Nombre',
      'ca': 'Nom',
      'en': 'Name',
      'eu': 'Izena',
      'fr': 'Nom',
      'gl': 'Nome',
    },
    '8j0toq1q': {
      'es': 'Apellidos',
      'ca': 'Cognoms',
      'en': 'Surnames',
      'eu': 'Abizenak',
      'fr': 'Noms de famille',
      'gl': 'Apelidos',
    },
    'dnag1d7s': {
      'es': 'Unidades de medida',
      'ca': 'Unitats de mesura',
      'en': 'Units of measurement',
      'eu': 'Neurri-unitateak',
      'fr': 'Unités de mesure',
      'gl': 'Unidades de medida',
    },
    'hvx3hgv8': {
      'es': 'kg / cm',
      'ca': 'kg/cm',
      'en': 'kg/cm',
      'eu': 'kg/cm',
      'fr': 'kg/cm',
      'gl': 'kg/cm',
    },
    'ymu4gmni': {
      'es': 'lb / inc',
      'ca': 'lb/inc',
      'en': 'lb/inc',
      'eu': 'lb/inc',
      'fr': 'lb/inc',
      'gl': 'lb/inc',
    },
    '08yoj4zs': {
      'es': 'Peso inicial',
      'ca': 'Pes inicial',
      'en': 'Initial weight',
      'eu': 'Hasierako pisua',
      'fr': 'Poids de départ',
      'gl': 'Peso inicial',
    },
    'l1byfy67': {
      'es': 'Altura',
      'ca': 'Alçada',
      'en': 'Height',
      'eu': 'Altuera',
      'fr': 'Hauteur',
      'gl': 'Altura',
    },
    '8onyjf32': {
      'es': 'Peso objetivo',
      'ca': 'Pes objectiu',
      'en': 'Target weight',
      'eu': 'Helburuko pisua',
      'fr': 'Poids cible',
      'gl': 'Peso obxectivo',
    },
    'edybn0bw': {
      'es': 'Info',
      'ca': 'Info',
      'en': 'Info',
      'eu': 'Info',
      'fr': 'Informations',
      'gl': 'Información',
    },
    '26nsoaos': {
      'es':
          'Reto Bariátrico ha sido desarrollado por TargetBox. Más información en www.retobariatrico.com',
      'ca':
          'Repte Bariàtric ha estat desenvolupat per TargetBox. Més informació a www.retobariatrico.com',
      'en':
          'Bariatric Challenge has been developed by TargetBox. More information at www.retobariatrico.com',
      'eu':
          'Bariatric Challenge TargetBox-ek garatu du. Informazio gehiago www.retobariatrico.com webgunean',
      'fr':
          'Bariatric Challenge a été développé par TargetBox. Plus d’informations sur www.retobariatrico.com',
      'gl':
          'Desafío bariátrico foi desenvolvido por TargetBox. Máis información en www.retobariatrico.com',
    },
    '615hx4gr': {
      'es': 'Reto Bariátrico',
      'ca': 'Repte Bariàtric',
      'en': 'Bariatric Challenge',
      'eu': 'Erronka Bariatrikoa',
      'fr': 'Défi bariatrique',
      'gl': 'Desafío Bariátrico',
    },
    'rvz7fzg5': {
      'es': 'TargetBox',
      'ca': 'TargetBox',
      'en': 'TargetBox',
      'eu': 'TargetBox',
      'fr': 'BoîteCible',
      'gl': 'TargetBox',
    },
    'nz1cig8q': {
      'es': 'check.io',
      'ca': 'check.io',
      'en': 'check.io',
      'eu': 'egiaztatu.io',
      'fr': 'check.io',
      'gl': 'comprobar.io',
    },
    'qrn52458': {
      'es': 'Dashboard',
      'ca': 'Dashboard',
      'en': 'Dashboard',
      'eu': 'Aginte-panela',
      'fr': 'Tableau de bord',
      'gl': 'Panel de control',
    },
    'jkutz0b5': {
      'es': 'Chats',
      'ca': 'Xats',
      'en': 'Chats',
      'eu': 'Txatak',
      'fr': 'Discussions',
      'gl': 'Chats',
    },
    'b2f9h2bd': {
      'es': 'Projects',
      'ca': 'Projects',
      'en': 'Projects',
      'eu': 'Proiektuak',
      'fr': 'Projets',
      'gl': 'Proxectos',
    },
    'jh83lq2u': {
      'es': 'Users',
      'ca': 'Users',
      'en': 'Users',
      'eu': 'Erabiltzaileak',
      'fr': 'Utilisateurs',
      'gl': 'Usuarios',
    },
    '2a0hemjt': {
      'es': 'Andrew D.',
      'ca': 'Andrew D.',
      'en': 'Andrew D.',
      'eu': 'Andres D.',
      'fr': 'Andrew D.',
      'gl': 'Andrés D.',
    },
    'yq51udia': {
      'es': 'admin@gmail.com',
      'ca': 'admin@gmail.com',
      'en': 'admin@gmail.com',
      'eu': 'admin@gmail.com',
      'fr': 'admin@gmail.com',
      'gl': 'admin@gmail.com',
    },
    '4q02oed7': {
      'es': 'Cerrar sesión',
      'ca': 'Tancar sessió',
      'en': 'Log out',
      'eu': 'Amaitu saioa',
      'fr': 'se déconnecter',
      'gl': 'Pechar sesión',
    },
    '8wf23ylu': {
      'es': 'Guardar',
      'ca': 'Desa',
      'en': 'Keep',
      'eu': 'Mantendu',
      'fr': 'Garder',
      'gl': 'Manteña',
    },
    '5pc5i4nz': {
      'es': 'Perfil',
      'ca': 'Perfil',
      'en': 'Profile',
      'eu': 'Profila',
      'fr': 'Profil',
      'gl': 'Perfil',
    },
    'd6bhl6w9': {
      'es': 'Perfil',
      'ca': 'Perfil',
      'en': 'Profile',
      'eu': 'Profila',
      'fr': 'Profil',
      'gl': 'Perfil',
    },
  },
  // Weight
  {
    'rugdp8q0': {
      'es':
          'Recuerda guardar tu peso inicial, peso objetivo y altura, para mostrar toda la información correctamente.',
      'ca':
          'Recorda desar el teu pes inicial, pes objectiu i alçada, per mostrar tota la informació correctament.',
      'en':
          'Remember to save your initial weight, target weight and height, to display all the information correctly.',
      'eu':
          'Gogoratu zure hasierako pisua, helburuko pisua eta altuera gordetzea, informazio guztia behar bezala bistaratzeko.',
      'fr':
          'Pensez à sauvegarder votre poids de départ, votre poids cible et votre taille, pour afficher correctement toutes les informations.',
      'gl':
          'Lembra gardar o teu peso inicial, peso obxectivo e altura, para mostrar toda a información correctamente.',
    },
    '43a4st6n': {
      'es': 'Inicial',
      'ca': 'Inicial',
      'en': 'Initial',
      'eu': 'Hasierakoa',
      'fr': 'Initial',
      'gl': 'Inicial',
    },
    'b7spv9wv': {
      'es': 'IMC',
      'ca': 'IMC',
      'en': 'BMI',
      'eu': 'GMI',
      'fr': 'IMC',
      'gl': 'IMC',
    },
    '29g5lind': {
      'es': 'Actual',
      'ca': 'Actual',
      'en': 'Current',
      'eu': 'Oraingoa',
      'fr': 'Actuel',
      'gl': 'Actual',
    },
    'mn6h2u6g': {
      'es': 'IMC',
      'ca': 'IMC',
      'en': 'BMI',
      'eu': 'GMI',
      'fr': 'IMC',
      'gl': 'IMC',
    },
    'chsgb58u': {
      'es': 'Objetivo',
      'ca': 'Objectiu',
      'en': 'Aim',
      'eu': 'Helburua',
      'fr': 'But',
      'gl': 'Apuntar',
    },
    'reco510k': {
      'es': 'IMC',
      'ca': 'IMC',
      'en': 'BMI',
      'eu': 'GMI',
      'fr': 'IMC',
      'gl': 'IMC',
    },
    'etk67hnj': {
      'es': 'Perdiste: ',
      'ca': 'Vas perdre:',
      'en': 'You lost:',
      'eu': 'Galdu duzu:',
      'fr': 'Vous avez perdu :',
      'gl': 'Perdeches:',
    },
    'ix2h6s83': {
      'es': 'Restante: ',
      'ca': 'Restant:',
      'en': 'Remaining:',
      'eu': 'Gainerakoak:',
      'fr': 'Restant:',
      'gl': 'Restante:',
    },
    '91kpo77l': {
      'es': 'Mes a mes',
      'ca': 'Mes a mes',
      'en': 'Month by month',
      'eu': 'hilabetez hilabete',
      'fr': 'mois par mois',
      'gl': 'mes a mes',
    },
    '8t5kackx': {
      'es': 'Muestra de forma más visual tus datos y evolución.',
      'ca': 'Mostra de manera més visual les teves dades i evolució.',
      'en': 'Show your data and evolution in a more visual way.',
      'eu': 'Erakutsi zure datuak eta bilakaera modu bisualago batean.',
      'fr': 'Montrez vos données et leur évolution de manière plus visuelle.',
      'gl': 'Mostra os teus datos e evolución dunha forma máis visual.',
    },
    's3s51fsy': {
      'es': 'Opción en fase de pruebas',
      'ca': 'Opció en fase de proves',
      'en': 'Option in testing phase',
      'eu': 'Aukera proba fasean',
      'fr': 'Option en phase de test',
      'gl': 'Opción en fase de proba',
    },
    '7o852dm0': {
      'es': 'Ir',
      'ca': 'Anar',
      'en': 'Go',
      'eu': 'Zoaz',
      'fr': 'Aller',
      'gl': 'Vaia',
    },
    'x35y1bfj': {
      'es': 'Peso',
      'ca': 'Pes',
      'en': 'Weight',
      'eu': 'Pisua',
      'fr': 'Poids',
      'gl': 'Peso',
    },
    '5kd3tbpx': {
      'es': 'Peso',
      'ca': 'Pes',
      'en': 'Weight',
      'eu': 'Pisua',
      'fr': 'Poids',
      'gl': 'Peso',
    },
  },
  // weightDataList
  {
    'ggrn9426': {
      'es': 'Peso',
      'ca': 'Pes',
      'en': 'Weight',
      'eu': 'Pisua',
      'fr': 'Poids',
      'gl': 'Peso',
    },
    'r7nbxlov': {
      'es': 'Fecha',
      'ca': 'Data',
      'en': 'Date',
      'eu': 'Data',
      'fr': 'Date',
      'gl': 'Data',
    },
    'tu03x20z': {
      'es': 'Acción',
      'ca': 'Acció',
      'en': 'Action',
      'eu': 'Ekintza',
      'fr': 'Action',
      'gl': 'Acción',
    },
    'a061gqza': {
      'es': 'Listado pesos',
      'ca': 'Llistat pesos',
      'en': 'List of weights',
      'eu': 'Pisuen zerrenda',
      'fr': 'Liste des poids',
      'gl': 'Lista de pesos',
    },
    'a9eqm64x': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // Calendar
  {
    '07pz7ueb': {
      'es': 'Calendario',
      'ca': 'Calendari',
      'en': 'Calendar',
      'eu': 'Egutegia',
      'fr': 'Calendrier',
      'gl': 'Calendario',
    },
    's8vhvjmo': {
      'es': 'Resumen',
      'ca': 'Resum',
      'en': 'Summary',
      'eu': 'Laburpena',
      'fr': 'Résumé',
      'gl': 'Resumo',
    },
    'y8xyphb6': {
      'es': 'Peso',
      'ca': 'Pes',
      'en': 'Weight',
      'eu': 'Pisua',
      'fr': 'Poids',
      'gl': 'Peso',
    },
    '8s46d360': {
      'es': 'Agua',
      'ca': 'Aigua',
      'en': 'Water',
      'eu': 'Ura',
      'fr': 'Eau',
      'gl': 'Auga',
    },
    '91xz0a62': {
      'es': 'uds.',
      'ca': 'uds.',
      'en': 'You.',
      'eu': 'Zuk.',
      'fr': 'Toi.',
      'gl': 'Ti.',
    },
    'tdub5w26': {
      'es': 'Ejercicio',
      'ca': 'Exercici',
      'en': 'Exercise',
      'eu': 'Ariketa',
      'fr': 'Exercice',
      'gl': 'Exercicio',
    },
    '784qmjgo': {
      'es': 'min',
      'ca': 'min',
      'en': 'min',
      'eu': 'min',
      'fr': 'min',
      'gl': 'min',
    },
    'xk7u9ga4': {
      'es': 'Suplementos',
      'ca': 'Suplements',
      'en': 'Supplements',
      'eu': 'Osagarriak',
      'fr': 'Suppléments',
      'gl': 'Suplementos',
    },
    'saa5dun4': {
      'es': 'Estado de ánimo',
      'ca': 'Estat d\'ànim',
      'en': 'Mood',
      'eu': 'aldarte',
      'fr': 'humeur',
      'gl': 'estado de ánimo',
    },
    'mw525dwi': {
      'es': 'Alimentación',
      'ca': 'Alimentació',
      'en': 'Feeding',
      'eu': 'Elikadura',
      'fr': 'Alimentation',
      'gl': 'Alimentación',
    },
    'dj7he94l': {
      'es': 'Desayuno',
      'ca': 'Esmorzar',
      'en': 'Breakfast',
      'eu': 'Gosaria',
      'fr': 'Petit-déjeuner',
      'gl': 'Almorzo',
    },
    'f4860nh1': {
      'es': 'Dumping',
      'ca': 'Dumping',
      'en': 'Dumping',
      'eu': 'Zabortegia',
      'fr': 'Dumping',
      'gl': 'Vertido',
    },
    'nwzk95q1': {
      'es': 'Comida/Almuerzo',
      'ca': 'Dinar/Dinar',
      'en': 'Lunch/Lunch',
      'eu': 'Janaria/ Bazkaria',
      'fr': 'Nourriture/Déjeuner',
      'gl': 'Comida/Xantar',
    },
    'h6r3fh98': {
      'es': 'Dumping',
      'ca': 'Dumping',
      'en': 'Dumping',
      'eu': 'Zabortegia',
      'fr': 'Dumping',
      'gl': 'Vertido',
    },
    'h4fyywhr': {
      'es': 'Cena',
      'ca': 'Sopar',
      'en': 'Dinner',
      'eu': 'Afaria',
      'fr': 'Dîner',
      'gl': 'Cea',
    },
    'ku3mi84v': {
      'es': 'Dumping',
      'ca': 'Dumping',
      'en': 'Dumping',
      'eu': 'Zabortegia',
      'fr': 'Dumping',
      'gl': 'Vertido',
    },
    'rhk82oi1': {
      'es': 'Snacks',
      'ca': 'Snacks',
      'en': 'Snacks',
      'eu': 'Pintxoak',
      'fr': 'Collations',
      'gl': 'Merendas',
    },
    '7sx3qt07': {
      'es': 'Dumping',
      'ca': 'Dumping',
      'en': 'Dumping',
      'eu': 'Zabortegia',
      'fr': 'Dumping',
      'gl': 'Vertido',
    },
    'o7wrvo6w': {
      'es': 'Medidas',
      'ca': 'Mesures',
      'en': 'Measures',
      'eu': 'Neurriak',
      'fr': 'Mesures',
      'gl': 'Medidas',
    },
    'ohm6fq4n': {
      'es': 'Busto',
      'ca': 'Bust',
      'en': 'Bust',
      'eu': 'Bustoa',
      'fr': 'Bousiller',
      'gl': 'Busto',
    },
    'e9zumm51': {
      'es': 'Brazo',
      'ca': 'Braç',
      'en': 'Arm',
      'eu': 'Besoa',
      'fr': 'Bras',
      'gl': 'Brazo',
    },
    'jzuq8y5g': {
      'es': 'Cintura',
      'ca': 'Cintura',
      'en': 'Waist',
      'eu': 'Gerria',
      'fr': 'Taille',
      'gl': 'Cintura',
    },
    '02u4ghgm': {
      'es': 'Abdomen',
      'ca': 'Abdomen',
      'en': 'Abdomen',
      'eu': 'Abdomena',
      'fr': 'Abdomen',
      'gl': 'Abdome',
    },
    '65o25jot': {
      'es': 'Cadera',
      'ca': 'Maluc',
      'en': 'Hip',
      'eu': 'Aldaka',
      'fr': 'Hanche',
      'gl': 'Cadeira',
    },
    '2ieoqhla': {
      'es': 'Muslo',
      'ca': 'Cuixa',
      'en': 'Thigh',
      'eu': 'Izterra',
      'fr': 'Cuisse',
      'gl': 'Coxa',
    },
    'qf66usn9': {
      'es': 'Calendario',
      'ca': 'Calendari',
      'en': 'Calendar',
      'eu': 'Egutegia',
      'fr': 'Calendrier',
      'gl': 'Calendario',
    },
  },
  // Pills
  {
    '4cw2c7eg': {
      'es': 'Suplementos tomados',
      'ca': 'Suplements presos',
      'en': 'Supplements taken',
      'eu': 'Hartutako osagarriak',
      'fr': 'Suppléments pris',
      'gl': 'Suplementos tomados',
    },
    'u9qt9qn1': {
      'es': 'Suplementos / Día',
      'ca': 'Suplements / Dia',
      'en': 'Supplements / Day',
      'eu': 'Osagarriak / Eguna',
      'fr': 'Suppléments / Jour',
      'gl': 'Suplementos/día',
    },
    'nf7t3369': {
      'es': 'Editar suplementos',
      'ca': 'Editar suplements',
      'en': 'Edit supplements',
      'eu': 'Editatu osagarriak',
      'fr': 'Modifier les suppléments',
      'gl': 'Editar suplementos',
    },
    'wn412xh8': {
      'es': 'Suplementos',
      'ca': 'Suplements',
      'en': 'Supplements',
      'eu': 'Osagarriak',
      'fr': 'Suppléments',
      'gl': 'Suplementos',
    },
    '5168f4y1': {
      'es': 'Agua',
      'ca': 'Aigua',
      'en': 'Water',
      'eu': 'Ura',
      'fr': 'Eau',
      'gl': 'Auga',
    },
  },
  // pillsList
  {
    'xtn6sw54': {
      'es': 'Lista de Suplementos',
      'ca': 'Llista de Suplements',
      'en': 'List of Supplements',
      'eu': 'Zerrenda osagarria',
      'fr': 'Liste des suppléments',
      'gl': 'Lista de complementos',
    },
    'bnzdr5ap': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // Mood
  {
    'xnh4vgl0': {
      'es': '🙁',
      'ca': '🙁',
      'en': '🙁',
      'eu': '🙁',
      'fr': '🙁',
      'gl': '🙁',
    },
    '012z1ccc': {
      'es': '😍',
      'ca': '😍',
      'en': '😍',
      'eu': '😍',
      'fr': '😍',
      'gl': '😍',
    },
    'qwbx7xvb': {
      'es': '😜',
      'ca': '😜',
      'en': '😜',
      'eu': '😜',
      'fr': '😜',
      'gl': '😜',
    },
    '72jnlu8i': {
      'es': '🤬',
      'ca': '🤬',
      'en': '🤬',
      'eu': '🤬',
      'fr': '🤬',
      'gl': '🤬',
    },
    '32cur5rb': {
      'es': '🤮',
      'ca': '🤮',
      'en': '🤮',
      'eu': '🤮',
      'fr': '🤮',
      'gl': '🤮',
    },
    '2ibbyoks': {
      'es': '🥺',
      'ca': '🥺',
      'en': '🥺',
      'eu': '🥺',
      'fr': '🥺',
      'gl': '🥺',
    },
    'luzupqfv': {
      'es': '😆',
      'ca': '😆',
      'en': '😆',
      'eu': '😆',
      'fr': '😆',
      'gl': '😆',
    },
    '3otgqeqq': {
      'es': '😠',
      'ca': '😠',
      'en': '😠',
      'eu': '😠',
      'fr': '😠',
      'gl': '😠',
    },
    '5qfmj5sh': {
      'es': '😢',
      'ca': '😢',
      'en': '😢',
      'eu': '😢',
      'fr': '😢',
      'gl': '😢',
    },
    'baxffiq7': {
      'es': '😴',
      'ca': '😴',
      'en': '😴',
      'eu': '😴',
      'fr': '😴',
      'gl': '😴',
    },
    'tszsoc82': {
      'es': '😵‍💫',
      'ca': '😵‍💫',
      'en': '😵‍💫',
      'eu': '😵‍💫',
      'fr': '😵‍💫',
      'gl': '😵‍💫',
    },
    'n6nlj7iu': {
      'es': '🙂',
      'ca': '🙂',
      'en': '🙂',
      'eu': '🙂',
      'fr': '🙂',
      'gl': '🙂',
    },
    'q8p23liv': {
      'es': '🤒',
      'ca': '🤒',
      'en': '🤒',
      'eu': '🤒',
      'fr': '🤒',
      'gl': '🤒',
    },
    'y20lc0sk': {
      'es': '🤢',
      'ca': '🤢',
      'en': '🤢',
      'eu': '🤢',
      'fr': '🤢',
      'gl': '🤢',
    },
    'yh4yr43l': {
      'es': '🥳',
      'ca': '🥳',
      'en': '🥳',
      'eu': '🥳',
      'fr': '🥳',
      'gl': '🥳',
    },
    '0w9sn683': {
      'es': '🥶',
      'ca': '🥶',
      'en': '🥶',
      'eu': '🥶',
      'fr': '🥶',
      'gl': '🥶',
    },
    'vtbuuh47': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'ycr8ou1a': {
      'es': 'Guardar',
      'ca': 'Desa',
      'en': 'Keep',
      'eu': 'Mantendu',
      'fr': 'Garder',
      'gl': 'Manteña',
    },
    'j6awe6d2': {
      'es': 'Estado de ánimo',
      'ca': 'Estat d\'ànim',
      'en': 'Mood',
      'eu': 'aldarte',
      'fr': 'humeur',
      'gl': 'estado de ánimo',
    },
  },
  // weightMap
  {
    'dprx0ufi': {
      'es': 'Mes a mes',
      'ca': 'Mes a mes',
      'en': 'Month by month',
      'eu': 'hilabetez hilabete',
      'fr': 'mois par mois',
      'gl': 'mes a mes',
    },
    'ra4jfew3': {
      'es': 'Mostrar campo extra',
      'ca': 'Mostrar camp extra',
      'en': 'Show extra field',
      'eu': 'Erakutsi eremu gehigarria',
      'fr': 'Afficher le champ supplémentaire',
      'gl': 'Mostrar campo extra',
    },
    'z1f1q5y1': {
      'es':
          'Oculta o muestra la información previa a los bloques de los meses.',
      'ca': 'Oculta o mostra la informació prèvia als blocs dels mesos.',
      'en': 'Hide or show information before the month blocks.',
      'eu': 'Hilabete-blokeen aurreko informazioa ezkutatu edo erakusten du.',
      'fr': 'Masque ou affiche les informations précédant les blocs mensuels.',
      'gl': 'Oculta ou mostra a información anterior aos bloques do mes.',
    },
    'lu6vztv4': {
      'es': 'Selecciona la imagen de fondo',
      'ca': 'Selecciona la imatge de fons',
      'en': 'Select the background image',
      'eu': 'Hautatu atzeko planoko irudia',
      'fr': 'Sélectionnez l\'image d\'arrière-plan',
      'gl': 'Seleccione a imaxe de fondo',
    },
    'mnzck1gu': {
      'es': 'Editar',
      'ca': 'Edita',
      'en': 'Edit',
      'eu': 'Editatu',
      'fr': 'Modifier',
      'gl': 'Editar',
    },
    'kel7nbqm': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // Measures
  {
    '7t4bsjaf': {
      'es': 'Medidas',
      'ca': 'Mesures',
      'en': 'Measures',
      'eu': 'Neurriak',
      'fr': 'Mesures',
      'gl': 'Medidas',
    },
    'i43nr0bz': {
      'es': 'Insertar medidas',
      'ca': 'Inserir mesures',
      'en': 'Insert measures',
      'eu': 'Txertatu neurriak',
      'fr': 'Insérer des mesures',
      'gl': 'Inserir medidas',
    },
    'tva5t3aw': {
      'es': 'Medidas',
      'ca': 'Mesures',
      'en': 'Measures',
      'eu': 'Neurriak',
      'fr': 'Mesures',
      'gl': 'Medidas',
    },
    '1kfrc9lv': {
      'es': 'Antes',
      'ca': 'Abans',
      'en': 'Before',
      'eu': 'Aurretik',
      'fr': 'Avant',
      'gl': 'Antes',
    },
    'dkb1eda2': {
      'es': 'Ahora',
      'ca': 'Ara',
      'en': 'Now',
      'eu': 'Orain',
      'fr': 'Maintenant',
      'gl': 'Agora',
    },
    'r3urgivo': {
      'es': 'Busto',
      'ca': 'Bust',
      'en': 'Bust',
      'eu': 'Bustoa',
      'fr': 'Bousiller',
      'gl': 'Busto',
    },
    '8my86wks': {
      'es': 'Brazo',
      'ca': 'Braç',
      'en': 'Arm',
      'eu': 'Besoa',
      'fr': 'Bras',
      'gl': 'Brazo',
    },
    'oa7dqoid': {
      'es': 'Cintura',
      'ca': 'Cintura',
      'en': 'Waist',
      'eu': 'Gerria',
      'fr': 'Taille',
      'gl': 'Cintura',
    },
    'dn25ietr': {
      'es': 'Abdomen',
      'ca': 'Abdomen',
      'en': 'Abdomen',
      'eu': 'Abdomena',
      'fr': 'Abdomen',
      'gl': 'Abdome',
    },
    '7uiv72h3': {
      'es': 'Cadera',
      'ca': 'Maluc',
      'en': 'Hip',
      'eu': 'Aldaka',
      'fr': 'Hanche',
      'gl': 'Cadeira',
    },
    'm9j2jhlv': {
      'es': 'Muslo',
      'ca': 'Cuixa',
      'en': 'Thigh',
      'eu': 'Izterra',
      'fr': 'Cuisse',
      'gl': 'Coxa',
    },
    'cdqfmchs': {
      'es': 'Antes',
      'ca': 'Abans',
      'en': 'Before',
      'eu': 'Aurretik',
      'fr': 'Avant',
      'gl': 'Antes',
    },
    '0r2js040': {
      'es': 'Fecha...',
      'ca': 'Data...',
      'en': 'Date...',
      'eu': 'Data...',
      'fr': 'Date...',
      'gl': 'Data...',
    },
    'k6cysnjo': {
      'es': 'Search for an item...',
      'ca': 'Search for an item...',
      'en': 'Search for an item...',
      'eu': 'Bilatu elementu bat...',
      'fr': 'Rechercher un article...',
      'gl': 'Busca un elemento...',
    },
    'azy0ch85': {
      'es': 'Option 1',
      'ca': 'Option 1',
      'en': 'Option 1',
      'eu': '1. aukera',
      'fr': 'Option 1',
      'gl': 'Opción 1',
    },
    '6jod28qo': {
      'es': 'Ahora',
      'ca': 'Ara',
      'en': 'Now',
      'eu': 'Orain',
      'fr': 'Maintenant',
      'gl': 'Agora',
    },
    '7ijlexy0': {
      'es': 'Fecha...',
      'ca': 'Data...',
      'en': 'Date...',
      'eu': 'Data...',
      'fr': 'Date...',
      'gl': 'Data...',
    },
    'bd7ocpo8': {
      'es': 'Search for an item...',
      'ca': 'Search for an item...',
      'en': 'Search for an item...',
      'eu': 'Bilatu elementu bat...',
      'fr': 'Rechercher un article...',
      'gl': 'Busca un elemento...',
    },
    '95lkzljs': {
      'es': 'Option 1',
      'ca': 'Option 1',
      'en': 'Option 1',
      'eu': '1. aukera',
      'fr': 'Option 1',
      'gl': 'Opción 1',
    },
    'shrk6mfm': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // measuresDataList
  {
    'degemm7e': {
      'es': 'Fecha',
      'ca': 'Data',
      'en': 'Date',
      'eu': 'Data',
      'fr': 'Date',
      'gl': 'Data',
    },
    'a75sf6mn': {
      'es': 'A',
      'ca': 'A',
      'en': 'TO',
      'eu': 'ERA',
      'fr': 'À',
      'gl': 'PARA',
    },
    'jx54f3fj': {
      'es': 'B',
      'ca': 'B',
      'en': 'B',
      'eu': 'b',
      'fr': 'b',
      'gl': 'b',
    },
    'uyhd1hw0': {
      'es': 'C',
      'ca': 'C',
      'en': 'C',
      'eu': 'c',
      'fr': 'c',
      'gl': 'c',
    },
    'rxtl4rgt': {
      'es': 'D',
      'ca': 'D',
      'en': 'D',
      'eu': 'd',
      'fr': 'd',
      'gl': 'd',
    },
    '67uva9nf': {
      'es': 'E',
      'ca': 'E',
      'en': 'AND',
      'eu': 'ETA',
      'fr': 'ET',
      'gl': 'E',
    },
    'vvvvowes': {
      'es': 'F',
      'ca': 'F',
      'en': 'F',
      'eu': 'F',
      'fr': 'F',
      'gl': 'F',
    },
    'pavd68uc': {
      'es': 'Acción',
      'ca': 'Acció',
      'en': 'Action',
      'eu': 'Ekintza',
      'fr': 'Action',
      'gl': 'Acción',
    },
    'ptsse6wb': {
      'es': 'Listado medidas',
      'ca': 'Llistat mesures',
      'en': 'List of measures',
      'eu': 'Neurrien zerrenda',
      'fr': 'Liste des mesures',
      'gl': 'Lista de medidas',
    },
    'hec9xaws': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // moodDataList
  {
    '7dzi0omn': {
      'es': 'Fecha',
      'ca': 'Data',
      'en': 'Date',
      'eu': 'Data',
      'fr': 'Date',
      'gl': 'Data',
    },
    'z14ucnpp': {
      'es': 'Emoción',
      'ca': 'Emoció',
      'en': 'Emotion',
      'eu': 'Emozioa',
      'fr': 'Émotion',
      'gl': 'Emoción',
    },
    'a232dtv3': {
      'es': 'Descripción',
      'ca': 'Descripció',
      'en': 'Description',
      'eu': 'Deskribapena',
      'fr': 'Description',
      'gl': 'Descrición',
    },
    'y6qwxbmc': {
      'es': 'Listado emociones',
      'ca': 'Llistat emocions',
      'en': 'List of emotions',
      'eu': 'Emozioen zerrenda',
      'fr': 'Liste des émotions',
      'gl': 'Lista de emocións',
    },
    'bfs00ppq': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // Meals
  {
    'mtuyrmo4': {
      'es': 'Desayuno',
      'ca': 'Esmorzar',
      'en': 'Breakfast',
      'eu': 'Gosaria',
      'fr': 'Petit-déjeuner',
      'gl': 'Almorzo',
    },
    'x4rpr2kc': {
      'es': 'Dumping',
      'ca': 'Dumping',
      'en': 'Dumping',
      'eu': 'Zabortegia',
      'fr': 'Dumping',
      'gl': 'Vertido',
    },
    '2cxi4xo8': {
      'es': 'Comida / Almuerzo',
      'ca': 'Dinar / Dinar',
      'en': 'Lunch / Dinner',
      'eu': 'Janaria/ Bazkaria',
      'fr': 'Nourriture/Déjeuner',
      'gl': 'Comida/Xantar',
    },
    'pdb4osch': {
      'es': 'Dumping',
      'ca': 'Dumping',
      'en': 'Dumping',
      'eu': 'Zabortegia',
      'fr': 'Dumping',
      'gl': 'Vertido',
    },
    'kfid1fcu': {
      'es': 'Cena',
      'ca': 'Sopar',
      'en': 'Dinner',
      'eu': 'Afaria',
      'fr': 'Dîner',
      'gl': 'Cea',
    },
    '39s9fgjl': {
      'es': 'Dumping',
      'ca': 'Dumping',
      'en': 'Dumping',
      'eu': 'Zabortegia',
      'fr': 'Dumping',
      'gl': 'Vertido',
    },
    'd5e0ufkm': {
      'es': 'Snacks',
      'ca': 'Snacks',
      'en': 'Snacks',
      'eu': 'Pintxoak',
      'fr': 'Collations',
      'gl': 'Merendas',
    },
    '0a6x4cr2': {
      'es': 'Dumping',
      'ca': 'Dumping',
      'en': 'Dumping',
      'eu': 'Zabortegia',
      'fr': 'Dumping',
      'gl': 'Vertido',
    },
    'vdqn7plx': {
      'es': 'Guardar',
      'ca': 'Desa',
      'en': 'Keep',
      'eu': 'Mantendu',
      'fr': 'Garder',
      'gl': 'Manteña',
    },
    'lc2zz1ui': {
      'es': 'Alimentación',
      'ca': 'Alimentació',
      'en': 'Feeding',
      'eu': 'Elikadura',
      'fr': 'Alimentation',
      'gl': 'Alimentación',
    },
    '1tzhtu8k': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // Workout
  {
    'x8rn23am': {
      'es': 'Tiempo de ejercicio',
      'ca': 'Temps d\'exercici',
      'en': 'Exercise time',
      'eu': 'ariketa denbora',
      'fr': 'temps d\'exercice',
      'gl': 'tempo de exercicio',
    },
    '6wudsse0': {
      'es': 'min',
      'ca': 'min',
      'en': 'min',
      'eu': 'min',
      'fr': 'min',
      'gl': 'min',
    },
    'cwkujzv2': {
      'es': 'Duración: ',
      'ca': 'Durada:',
      'en': 'Duration:',
      'eu': 'Iraupena:',
      'fr': 'Durée:',
      'gl': 'Duración:',
    },
    '7i3tflny': {
      'es': 'Actualizar ejercicio',
      'ca': 'Actualitzar exercici',
      'en': 'Update exercise',
      'eu': 'Eguneratzeko ariketa',
      'fr': 'Exercice de mise à jour',
      'gl': 'Exercicio de actualización',
    },
    'z5xs9y0o': {
      'es': 'Actualizar',
      'ca': 'Actualitzar',
      'en': 'Update',
      'eu': 'Eguneratu',
      'fr': 'Mise à jour',
      'gl': 'Actualizar',
    },
    'nlqxwo40': {
      'es': 'Ejercicio',
      'ca': 'Exercici',
      'en': 'Exercise',
      'eu': 'Ariketa',
      'fr': 'Exercice',
      'gl': 'Exercicio',
    },
    'tpg8h0ug': {
      'es': 'Añadir ejercicio',
      'ca': 'Afegir exercici',
      'en': 'Add exercise',
      'eu': 'Gehitu ariketa',
      'fr': 'Ajouter un exercice',
      'gl': 'Engadir exercicio',
    },
    'gxx0oqlr': {
      'es': 'Añadir',
      'ca': 'Afegir',
      'en': 'Add',
      'eu': 'Gehitu',
      'fr': 'Ajouter',
      'gl': 'Engadir',
    },
    'fopcpzfn': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // mealsDataList
  {
    'bwzts4ms': {
      'es': 'Fecha',
      'ca': 'Data',
      'en': 'Date',
      'eu': 'Data',
      'fr': 'Date',
      'gl': 'Data',
    },
    'bl4f5w3v': {
      'es': 'Acción',
      'ca': 'Acció',
      'en': 'Action',
      'eu': 'Ekintza',
      'fr': 'Action',
      'gl': 'Acción',
    },
    'ukeztbas': {
      'es': 'Ver/Editar',
      'ca': 'Veure/Editar',
      'en': 'View/Edit',
      'eu': 'Ikusi/Editatu',
      'fr': 'Afficher/Modifier',
      'gl': 'Ver/Editar',
    },
    'p1a7dcxu': {
      'es': 'Eliminar',
      'ca': 'Eliminar',
      'en': 'Eliminate',
      'eu': 'Ezabatu',
      'fr': 'Éliminer',
      'gl': 'Eliminar',
    },
    'pb1s2n7b': {
      'es': 'Listado alimentación',
      'ca': 'Llistat alimentació',
      'en': 'List of feed',
      'eu': 'Elikagaien zerrenda',
      'fr': 'Liste des aliments',
      'gl': 'Lista de alimentos',
    },
    'id2ca8gk': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // workoutsDataList
  {
    'xfjgvj9s': {
      'es': 'Fecha',
      'ca': 'Data',
      'en': 'Date',
      'eu': 'Data',
      'fr': 'Date',
      'gl': 'Data',
    },
    'grnlpouo': {
      'es': 'Duración Total',
      'ca': 'Durada Total',
      'en': 'Total Duration',
      'eu': 'Iraupen osoa',
      'fr': 'Durée totale',
      'gl': 'Duración total',
    },
    'r5g1rwp6': {
      'es': 'min',
      'ca': 'min',
      'en': 'min',
      'eu': 'min',
      'fr': 'min',
      'gl': 'min',
    },
    'vwuxvthy': {
      'es': 'Acción',
      'ca': 'Acció',
      'en': 'Action',
      'eu': 'Ekintza',
      'fr': 'Action',
      'gl': 'Acción',
    },
    'ayc66wqd': {
      'es': 'Listado ejercicios',
      'ca': 'Llistat exercicis',
      'en': 'List of exercises',
      'eu': 'Ariketen zerrenda',
      'fr': 'Liste des exercices',
      'gl': 'Lista de exercicios',
    },
    'my71b89z': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // Welcome
  {
    'eeczbfzq': {
      'es': 'Nueva cuenta',
      'ca': 'Nou compte',
      'en': 'New account',
      'eu': 'Kontu berria',
      'fr': 'Nouveau compte',
      'gl': 'Nova conta',
    },
    'db6gg63h': {
      'es': 'Crear ',
      'ca': 'Crear',
      'en': 'Create',
      'eu': 'Sortu',
      'fr': 'Créer',
      'gl': 'Crear',
    },
    'oulrhjtk': {
      'es': 'Empieza rápidamente creando tu cuenta',
      'ca': 'Comença ràpidament creant el teu compte',
      'en': 'Get started quickly by creating your account',
      'eu': 'Hasi azkar zure kontua sortuz',
      'fr': 'Commencez vite en créant votre compte',
      'gl': 'Comeza rapidamente creando a túa conta',
    },
    '8in2chpa': {
      'es': 'Nombre',
      'ca': 'Nom',
      'en': 'Name',
      'eu': 'Izena',
      'fr': 'Nom',
      'gl': 'Nome',
    },
    'z3d3n7z5': {
      'es': 'Email',
      'ca': 'Email',
      'en': 'E-mail',
      'eu': 'Posta elektronikoa',
      'fr': 'E-mail',
      'gl': 'Correo electrónico',
    },
    '2jm1ys67': {
      'es': 'Contraseña',
      'ca': 'Contrasenya',
      'en': 'Password',
      'eu': 'Pasahitza',
      'fr': 'Mot de passe',
      'gl': 'Contrasinal',
    },
    'nfipgfat': {
      'es': 'Este campo es requerido',
      'ca': 'Aquest camp és requerit',
      'en': 'This field is required',
      'eu': 'Eremu hau beharrezkoa da',
      'fr': 'Ce champ est obligatoire',
      'gl': 'Este campo é obrigatorio',
    },
    '6rwdvrke': {
      'es': 'Permitido máximo de 20 caracteres',
      'ca': 'Permès màxim de 20 caràcters',
      'en': 'Maximum allowed 20 characters',
      'eu': 'Gehienez 20 karaktere onartzen dira',
      'fr': 'Maximum autorisé 20 caractères',
      'gl': 'Máximo permitido 20 caracteres',
    },
    'sbsxb5db': {
      'es': 'El campo Nombre no es correcto',
      'ca': 'El camp Nom no és correcte',
      'en': 'The Name field is not correct',
      'eu': 'Izenaren eremua ez da zuzena',
      'fr': 'Le champ du nom n\'est pas correct',
      'gl': 'O campo do nome non é correcto',
    },
    'jbwx39km': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    'cvypx1ji': {
      'es': 'Este campo es requerido',
      'ca': 'Aquest camp és requerit',
      'en': 'This field is required',
      'eu': 'Eremu hau beharrezkoa da',
      'fr': 'Ce champ est obligatoire',
      'gl': 'Este campo é obrigatorio',
    },
    'ly41k1l0': {
      'es': 'Requerido mínimo 6 caracteres',
      'ca': 'Requerit mínim 6 caràcters',
      'en': 'Minimum required 6 characters',
      'eu': 'Gutxienez 6 karaktere behar dira',
      'fr': 'Minimum 6 caractères requis',
      'gl': 'Requírense un mínimo de 6 caracteres',
    },
    'fccjflj4': {
      'es': 'El campo Email no es corecto',
      'ca': 'El camp Email no és correcte',
      'en': 'The Email field is not correct',
      'eu': 'Posta elektronikoa eremua ez da zuzena',
      'fr': 'Le champ Email n\'est pas correct',
      'gl': 'O campo Correo electrónico non é correcto',
    },
    'xgwx1rja': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    '25i83syp': {
      'es': 'Este campo es requerido',
      'ca': 'Aquest camp és requerit',
      'en': 'This field is required',
      'eu': 'Eremu hau beharrezkoa da',
      'fr': 'Ce champ est obligatoire',
      'gl': 'Este campo é obrigatorio',
    },
    'jrkmedsv': {
      'es': 'La contraseña debe tener mínimo 8 carácteres.',
      'ca': 'La contrasenya ha de tenir un mínim de 8 caràcters.',
      'en': 'The password must be at least 8 characters long.',
      'eu': 'Pasahitzak 8 karaktere izan behar ditu gutxienez.',
      'fr': 'Le mot de passe doit comporter un minimum de 8 caractères.',
      'gl': 'O contrasinal debe ter un mínimo de 8 caracteres.',
    },
    'ajz82vk0': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    '6lw5u4qk': {
      'es':
          'Acepto y conozco las condiciones de uso. Más información en el enlace:',
      'ca': 'Accepto i conec les condicions dús. Més informació a l\'enllaç:',
      'en':
          'I accept and understand the terms of use. More information at the link:',
      'eu':
          'Erabilera baldintzak onartzen eta ezagutzen ditut. Informazio gehiago estekan:',
      'fr':
          'J\'accepte et connais les conditions d\'utilisation. Plus d\'informations sur le lien :',
      'gl':
          'Acepto e coñezo as condicións de uso. Máis información na ligazón:',
    },
    'wybqk94r': {
      'es': 'Ver términos de uso',
      'ca': 'Veure termes dús',
      'en': 'See terms of use',
      'eu': 'Ikusi erabilera baldintzak',
      'fr': 'Voir conditions d\'utilisation',
      'gl': 'Consulta as condicións de uso',
    },
    '8gvz1mp9': {
      'es': 'Crear',
      'ca': 'Crear',
      'en': 'Create',
      'eu': 'Sortu',
      'fr': 'Créer',
      'gl': 'Crear',
    },
    'le34wiig': {
      'es': 'Entrar',
      'ca': 'Entrar',
      'en': 'Log in',
      'eu': 'Sartu',
      'fr': 'Entrer',
      'gl': 'Entra',
    },
    'in8jim5x': {
      'es': '¡Hola!',
      'ca': 'Hola!',
      'en': 'Hello!',
      'eu': 'Kaixo!',
      'fr': 'Bonjour!',
      'gl': 'Ola!',
    },
    'lej3qh51': {
      'es': 'Rellena tus datos de acceso',
      'ca': 'Omple les teves dades d\'accés',
      'en': 'Fill in your access data',
      'eu': 'Bete zure sarbide-informazioa',
      'fr': 'Remplissez vos informations d\'accès',
      'gl': 'Completa a túa información de acceso',
    },
    '4bspyxh6': {
      'es': '',
      'ca': 'Email',
      'en': 'E-mail',
      'eu': 'Posta elektronikoa',
      'fr': 'E-mail',
      'gl': 'Correo electrónico',
    },
    'al0wzvn1': {
      'es': 'Email',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'tix628yj': {
      'es': '',
      'ca': 'Contrasenya',
      'en': 'Password',
      'eu': 'Pasahitza',
      'fr': 'Mot de passe',
      'gl': 'Contrasinal',
    },
    '3giasn6h': {
      'es': 'Contraseña',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'g6ima11a': {
      'es': 'Campo requerido',
      'ca': 'Camp requerit',
      'en': 'Required field',
      'eu': 'Beharrezko eremua',
      'fr': 'Champ obligatoire',
      'gl': 'Campo obrigatorio',
    },
    'wzghni4j': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    'qpvtthsq': {
      'es': 'Campo requerido',
      'ca': 'Camp requerit',
      'en': 'Required field',
      'eu': 'Beharrezko eremua',
      'fr': 'Champ obligatoire',
      'gl': 'Campo obrigatorio',
    },
    'g308msiy': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    '54uqm0gh': {
      'es': 'Entrar',
      'ca': 'Entrar',
      'en': 'Enter',
      'eu': 'Sartu',
      'fr': 'Entrer',
      'gl': 'Entra',
    },
    'xobud8j3': {
      'es': '¿Olvidaste la contraseña?',
      'ca': 'Has oblidat la contrasenya?',
      'en': 'Forgot your password?',
      'eu': 'Pasahitza ahaztu al duzu?',
      'fr': 'Vous avez oublié votre mot de passe ?',
      'gl': 'Esqueceches o teu contrasinal?',
    },
    'tt89r8kp': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // forgotPassword
  {
    '853gkocw': {
      'es': 'Back',
      'ca': 'Back',
      'en': 'Back',
      'eu': 'Itzuli',
      'fr': 'Dos',
      'gl': 'De volta',
    },
    'oteasi2f': {
      'es': 'Cambiar Contraseña',
      'ca': 'Canviar Contrasenya',
      'en': 'Change Password',
      'eu': 'Aldatu pasahitza',
      'fr': 'Changer le mot de passe',
      'gl': 'Cambiar contrasinal',
    },
    'ziea4cxi': {
      'es':
          'Se enviará un email con un enlace para que puedas modificar tu contraseña.',
      'ca':
          'S\'enviarà un correu electrònic amb un enllaç perquè puguis modificar la teva contrasenya.',
      'en':
          'An email will be sent with a link so you can change your password.',
      'eu':
          'Mezu elektroniko bat bidaliko da esteka batekin, pasahitza alda dezazun.',
      'fr':
          'Un email vous sera envoyé avec un lien afin que vous puissiez modifier votre mot de passe.',
      'gl':
          'Enviarase un correo electrónico cunha ligazón para que poidas cambiar o teu contrasinal.',
    },
    'zh7z3yos': {
      'es': 'Tu email...',
      'ca': 'El teu email...',
      'en': 'Your email...',
      'eu': 'Zure e-posta...',
      'fr': 'Votre email...',
      'gl': 'O teu correo electrónico...',
    },
    'cotbo8i9': {
      'es': 'Introduzca su email...',
      'ca': 'Introduïu el vostre email...',
      'en': 'Enter your email...',
      'eu': 'Sartu zure helbide elektronikoa...',
      'fr': 'Entrez votre email...',
      'gl': 'Introduce o teu correo electrónico...',
    },
    'edq1z1hd': {
      'es': 'Enviar enlace',
      'ca': 'Enviar enllaç',
      'en': 'Send link',
      'eu': 'Bidali esteka',
      'fr': 'Envoyer le lien',
      'gl': 'Enviar ligazón',
    },
    'hdee084d': {
      'es': 'Volver',
      'ca': 'Tornar',
      'en': 'Return',
      'eu': 'Itzuli',
      'fr': 'Retour',
      'gl': 'Volver',
    },
    'sk293hxf': {
      'es': 'Home',
      'ca': 'Home',
      'en': 'Home',
      'eu': 'Hasiera',
      'fr': 'Maison',
      'gl': 'Casa',
    },
  },
  // RinconBariatrico
  {
    '99bbgz4i': {
      'es': 'Rincón Bariátrico',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'pd50s80o': {
      'es': 'BariaLinks',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'x6f1cd88': {
      'es': 'Comunidad diseñada por y para usuarios bariátricos.',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'iqw920ou': {
      'es': 'Home',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
  },
  // modalActualizarRetoAgua
  {
    'rozx57sh': {
      'es': 'Cantidad vasos de agua',
      'ca': 'Quantitat gots d\'aigua',
      'en': 'Number of glasses of water',
      'eu': 'Ur edalontzi kopurua',
      'fr': 'Quantité verres d\'eau',
      'gl': 'Cantidade vasos de auga',
    },
    'qkjbnth9': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    '93aagu65': {
      'es': 'Cantidad de vasos de agua que consumirás de forma diaria.',
      'ca': 'Quantitat de gots d\'aigua que consumiràs diàriament.',
      'en': 'Number of glasses of water you will consume daily.',
      'eu': 'Egunero kontsumituko dituzun ur edalontzi kopurua.',
      'fr': 'Nombre de verres d\'eau que vous consommerez quotidiennement.',
      'gl': 'Número de vasos de auga que consumirás diariamente.',
    },
    'wlogogrb': {
      'es': 'Guardar',
      'ca': 'Desa',
      'en': 'Keep',
      'eu': 'Mantendu',
      'fr': 'Garder',
      'gl': 'Manteña',
    },
  },
  // modalAddPeso
  {
    'tv6gqugl': {
      'es': 'Registrar peso',
      'ca': 'Registrar pes',
      'en': 'Record weight',
      'eu': 'Pisu errekorra',
      'fr': 'Poids record',
      'gl': 'Rexistro de peso',
    },
    'jg18t200': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'hc043de7': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'd73kiami': {
      'es': 'Valor incorrecto',
      'ca': 'Valor incorrecte',
      'en': 'Incorrect value',
      'eu': 'Balio okerra',
      'fr': 'Valeur incorrecte',
      'gl': 'Valor incorrecto',
    },
    's13taxd1': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    'i6skppdw': {
      'es': 'Guardar',
      'ca': 'Desa',
      'en': 'Keep',
      'eu': 'Mantendu',
      'fr': 'Garder',
      'gl': 'Manteña',
    },
  },
  // modalAddPill
  {
    'uhl25lok': {
      'es': 'Añadir suplemento',
      'ca': 'Afegir suplement',
      'en': 'Add supplement',
      'eu': 'Gehitu osagarria',
      'fr': 'Ajouter un supplément',
      'gl': 'Engadir suplemento',
    },
    '1277dx4b': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'e8wmpj8a': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'b091i5dm': {
      'es': 'Valor incorrecto',
      'ca': 'Valor incorrecte',
      'en': 'Incorrect value',
      'eu': 'Balio okerra',
      'fr': 'Valeur incorrecte',
      'gl': 'Valor incorrecto',
    },
    'gxtxl2xx': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    '1d7yhay1': {
      'es': 'Añadir',
      'ca': 'Afegir',
      'en': 'Add',
      'eu': 'Gehitu',
      'fr': 'Ajouter',
      'gl': 'Engadir',
    },
  },
  // modalModifyPill
  {
    'mug9b4x4': {
      'es': 'Modificar suplemento',
      'ca': 'Modificar suplement',
      'en': 'Modify supplement',
      'eu': 'Gehigarria aldatu',
      'fr': 'Modifier le supplément',
      'gl': 'Modificar suplemento',
    },
    'c1s8as1n': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'wf14usjy': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'b9ihpo8p': {
      'es': 'Valor incorrecto',
      'ca': 'Valor incorrecte',
      'en': 'Incorrect value',
      'eu': 'Balio okerra',
      'fr': 'Valeur incorrecte',
      'gl': 'Valor incorrecto',
    },
    'ihehzvh2': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    '4dl5ttwl': {
      'es': 'Guardar',
      'ca': 'Desa',
      'en': 'Keep',
      'eu': 'Mantendu',
      'fr': 'Garder',
      'gl': 'Manteña',
    },
  },
  // CustomIcon
  {
    'm072s4vl': {
      'es': '🥶',
      'ca': '🥶',
      'en': '🥶',
      'eu': '🥶',
      'fr': '🥶',
      'gl': '🥶',
    },
    '6rjl0e23': {
      'es': '🫥',
      'ca': '🫥',
      'en': '🫥',
      'eu': '🫥',
      'fr': '🫥',
      'gl': '🫥',
    },
    'khlznhqh': {
      'es': '☹️',
      'ca': '☹️',
      'en': '☹️',
      'eu': '☹️',
      'fr': '☹️',
      'gl': '☹️',
    },
    'q5w2t5po': {
      'es': '😍',
      'ca': '😍',
      'en': '😍',
      'eu': '😍',
      'fr': '😍',
      'gl': '😍',
    },
    '8qo3xsjb': {
      'es': '😜',
      'ca': '😜',
      'en': '😜',
      'eu': '😜',
      'fr': '😜',
      'gl': '😜',
    },
    '7yysjk8o': {
      'es': '🤬',
      'ca': '🤬',
      'en': '🤬',
      'eu': '🤬',
      'fr': '🤬',
      'gl': '🤬',
    },
    'ukn36lj2': {
      'es': '🤮',
      'ca': '🤮',
      'en': '🤮',
      'eu': '🤮',
      'fr': '🤮',
      'gl': '🤮',
    },
    'kc8s2x1e': {
      'es': '🥺',
      'ca': '🥺',
      'en': '🥺',
      'eu': '🥺',
      'fr': '🥺',
      'gl': '🥺',
    },
    '39lleqp7': {
      'es': '😆',
      'ca': '😆',
      'en': '😆',
      'eu': '😆',
      'fr': '😆',
      'gl': '😆',
    },
    'dhklq8to': {
      'es': '😠',
      'ca': '😠',
      'en': '😠',
      'eu': '😠',
      'fr': '😠',
      'gl': '😠',
    },
    'jak3th7p': {
      'es': '😢',
      'ca': '😢',
      'en': '😢',
      'eu': '😢',
      'fr': '😢',
      'gl': '😢',
    },
    'pm69ztkh': {
      'es': '😴',
      'ca': '😴',
      'en': '😴',
      'eu': '😴',
      'fr': '😴',
      'gl': '😴',
    },
    '9vlfa9cz': {
      'es': '😵‍💫',
      'ca': '😵‍💫',
      'en': '😵‍💫',
      'eu': '😵‍💫',
      'fr': '😵‍💫',
      'gl': '😵‍💫',
    },
    'yyr5w96o': {
      'es': '🙂',
      'ca': '🙂',
      'en': '🙂',
      'eu': '🙂',
      'fr': '🙂',
      'gl': '🙂',
    },
    'fg4t09n5': {
      'es': '🤒',
      'ca': '🤒',
      'en': '🤒',
      'eu': '🤒',
      'fr': '🤒',
      'gl': '🤒',
    },
    'liepkyr3': {
      'es': '🤢',
      'ca': '🤢',
      'en': '🤢',
      'eu': '🤢',
      'fr': '🤢',
      'gl': '🤢',
    },
    '4k9shcm5': {
      'es': '🥳',
      'ca': '🥳',
      'en': '🥳',
      'eu': '🥳',
      'fr': '🥳',
      'gl': '🥳',
    },
  },
  // modalWeightMap
  {
    'seqxcceh': {
      'es': 'Editar - Mes a mes',
      'ca': 'Edita - Mes a mes',
      'en': 'Edit - Month by month',
      'eu': 'Editatu - Hilabetez hilabete',
      'fr': 'Modifier - Mois par mois',
      'gl': 'Editar - Mes a mes',
    },
    'pfanyzte': {
      'es':
          'Aporta toda la información posible para poder generar el Mes a Mes de tu reto bariátrico. No olvides añadir el valor inicial para poder calcular el resto de valores para los próximos meses.',
      'ca':
          'Aporta tota la informació possible per poder generar el Mes a Mes del teu repte bariàtric. No oblidis afegir el valor inicial per poder calcular la resta de valors per als propers mesos.',
      'en':
          'Provide as much information as possible to generate the Month by Month of your bariatric challenge. Don\'t forget to add the initial value to be able to calculate the rest of the values for the following months.',
      'eu':
          'Eman informazio guztia zure erronka bariatrikoa hilabetez hilabete sortu ahal izateko. Ez ahaztu hasierako balioa gehitzea datozen hilabeteetarako gainerako balioak kalkulatu ahal izateko.',
      'fr':
          'Fournissez toutes les informations possibles pour pouvoir générer le Mois par Mois de votre défi bariatrique. N\'oubliez pas d\'ajouter la valeur initiale pour pouvoir calculer le reste des valeurs pour les mois à venir.',
      'gl':
          'Proporciona toda a información posible para poder xerar o mes a mes do teu reto bariátrico. Non esquezas engadir o valor inicial para poder calcular o resto dos valores para os próximos meses.',
    },
    'tg1swhg9': {
      'es': 'Título',
      'ca': 'Títol',
      'en': 'Qualification',
      'eu': 'Titulazioa',
      'fr': 'Qualification',
      'gl': 'Cualificación',
    },
    'vl8z3n5o': {
      'es': 'Texto de valor inicial',
      'ca': 'Text de valor inicial',
      'en': 'Initial value text',
      'eu': 'Hasierako balio-testua',
      'fr': 'Texte de la valeur initiale',
      'gl': 'Texto de valor inicial',
    },
    'usn2d2vb': {
      'es': 'Valor inicial',
      'ca': 'Valor inicial',
      'en': 'Initial value',
      'eu': 'Hasierako balioa',
      'fr': 'Valeur initiale',
      'gl': 'Valor inicial',
    },
    'z28dyydd': {
      'es': 'Valor diferencia',
      'ca': 'Valor diferència',
      'en': 'Value difference',
      'eu': 'Desberdintasunaren balioa',
      'fr': 'Valeur de différence',
      'gl': 'Valor da diferenza',
    },
    'vz2w18fp': {
      'es': 'Texto Mes 1',
      'ca': 'Text Mes 1',
      'en': 'Text Month 1',
      'eu': 'Testua 1. hilabetea',
      'fr': 'Texter le mois 1',
      'gl': 'Texto Mes 1',
    },
    '8yicee87': {
      'es': 'Valor Mes 1',
      'ca': 'Valor Mes 1',
      'en': 'Month 1 Value',
      'eu': 'Balioa 1. hilabetea',
      'fr': 'Valeur Mois 1',
      'gl': 'Valor mes 1',
    },
    'kjafio4s': {
      'es': 'Texto Mes 2',
      'ca': 'Text Mes 2',
      'en': 'Text Month 2',
      'eu': 'Testua 2. hilabetea',
      'fr': 'Texter le mois 2',
      'gl': 'Texto Mes 2',
    },
    'p15shjx7': {
      'es': 'Valor Mes 2',
      'ca': 'Valor Mes 2',
      'en': 'Month 2 Value',
      'eu': 'Balioa 2. hilabetea',
      'fr': 'Valeur Mois 2',
      'gl': 'Valor mes 2',
    },
    '0dq3r2pb': {
      'es': 'Texto Mes 3',
      'ca': 'Text Mes 3',
      'en': 'Text Month 3',
      'eu': 'Testua 3. hilabetea',
      'fr': 'Texter le mois 3',
      'gl': 'Texto Mes 3',
    },
    '2bmm27l2': {
      'es': 'Valor Mes 3',
      'ca': 'Valor Mes 3',
      'en': 'Month 3 Value',
      'eu': 'Balioa 3. hilabetea',
      'fr': 'Valeur Mois 3',
      'gl': 'Valor mes 3',
    },
    'zqdscjt7': {
      'es': 'Texto Mes 4',
      'ca': 'Text Mes 4',
      'en': 'Text Month 4',
      'eu': 'Testua 4. hilabetea',
      'fr': 'Texter le mois 4',
      'gl': 'Texto Mes 4',
    },
    'd8y464ih': {
      'es': 'Valor Mes 4',
      'ca': 'Valor Mes 4',
      'en': 'Month 4 Value',
      'eu': 'Balioa 4. hilabetea',
      'fr': 'Valeur Mois 4',
      'gl': 'Valor mes 4',
    },
    'ywk1rv76': {
      'es': 'Texto Mes 5',
      'ca': 'Text Mes 5',
      'en': 'Text Month 5',
      'eu': 'Testua 5. hilabetea',
      'fr': 'Texter le mois 5',
      'gl': 'Texto do mes 5',
    },
    '4ruzrflu': {
      'es': 'Valor Mes 5',
      'ca': 'Valor Mes 5',
      'en': 'Month 5 Value',
      'eu': 'Balioa 5. hilabetea',
      'fr': 'Valeur Mois 5',
      'gl': 'Valor mes 5',
    },
    'pcjx0ioq': {
      'es': 'Texto Mes 6',
      'ca': 'Text Mes 6',
      'en': 'Text Month 6',
      'eu': 'Testua 6. hilabetea',
      'fr': 'Texter le mois 6',
      'gl': 'Texto do mes 6',
    },
    's0rkvn67': {
      'es': 'Valor Mes 6',
      'ca': 'Valor Mes 6',
      'en': 'Month 6 Value',
      'eu': 'Balioa 6. hilabetea',
      'fr': 'Valeur Mois 6',
      'gl': 'Valor mes 6',
    },
    '6ov67280': {
      'es': 'Texto Mes 7',
      'ca': 'Text Mes 7',
      'en': 'Text Month 7',
      'eu': 'Testua 7. hilabetea',
      'fr': 'Texter le mois 7',
      'gl': 'Texto Mes 7',
    },
    'vnp6vqvs': {
      'es': 'Valor Mes 7',
      'ca': 'Valor Mes 7',
      'en': 'Month 7 Value',
      'eu': 'Balioa 7. hilabetea',
      'fr': 'Mois de valeur 7',
      'gl': 'Valor mes 7',
    },
    'uhu00r1z': {
      'es': 'Texto Mes 8',
      'ca': 'Text Mes 8',
      'en': 'Text Month 8',
      'eu': 'Testua 8. hilabetea',
      'fr': 'Texter le mois 8',
      'gl': 'Texto Mes 8',
    },
    '6hptvwmt': {
      'es': 'Valor Mes 8',
      'ca': 'Valor Mes 8',
      'en': 'Month 8 Value',
      'eu': 'Balioa 8. hilabetea',
      'fr': 'Mois de valeur 8',
      'gl': 'Valor mes 8',
    },
    'f7mnohog': {
      'es': 'Texto Mes 9',
      'ca': 'Text Mes 9',
      'en': 'Text Month 9',
      'eu': 'Testua 9. hilabetea',
      'fr': 'Envoyez un SMS au mois 9',
      'gl': 'Texto Mes 9',
    },
    'hetkz92u': {
      'es': 'Valor Mes 9',
      'ca': 'Valor Mes 9',
      'en': 'Month 9 Value',
      'eu': 'Balioa 9. hilabetea',
      'fr': 'Valeur Mois 9',
      'gl': 'Valor mes 9',
    },
    'tluidl51': {
      'es': 'Texto Mes 10',
      'ca': 'Text Mes 10',
      'en': 'Text Month 10',
      'eu': 'Testua hilabetea 10',
      'fr': 'Texter le mois 10',
      'gl': 'Texto mes 10',
    },
    'xd7q4leo': {
      'es': 'Valor Mes 10',
      'ca': 'Valor Mes 10',
      'en': 'Month 10 Value',
      'eu': 'Balioa 10. hilabetea',
      'fr': 'Valeur Mois 10',
      'gl': 'Valor mes 10',
    },
    'im2apbqs': {
      'es': 'Texto Mes 11',
      'ca': 'Text Mes 11',
      'en': 'Text Month 11',
      'eu': 'Testua hilabetea 11',
      'fr': 'Envoyez un SMS au mois 11',
      'gl': 'Texto Mes 11',
    },
    '1pxyf4mo': {
      'es': 'Valor Mes 11',
      'ca': 'Valor Mes 11',
      'en': 'Month 11 Value',
      'eu': 'Balioa 11. hilabetea',
      'fr': 'Mois de valeur 11',
      'gl': 'Valor mes 11',
    },
    'waaipg7r': {
      'es': 'Texto Mes 12',
      'ca': 'Text Mes 12',
      'en': 'Text Month 12',
      'eu': 'Testua 12. hilabetea',
      'fr': 'Texter le mois 12',
      'gl': 'Texto do mes 12',
    },
    'qioowms7': {
      'es': 'Valor Mes 12',
      'ca': 'Valor Mes 12',
      'en': 'Month 12 Value',
      'eu': 'Balioa 12. hilabetea',
      'fr': 'Mois de valeur 12',
      'gl': 'Valor mes 12',
    },
    'd0v2tm8v': {
      'es': 'Color del texto',
      'ca': 'Color del text',
      'en': 'Text color',
      'eu': 'Testuaren kolorea',
      'fr': 'Couleur du texte',
      'gl': 'Cor do texto',
    },
    'j3ros6m8': {
      'es': 'Color del mes',
      'ca': 'Color del mes',
      'en': 'Color of the month',
      'eu': 'Hileko kolorea',
      'fr': 'Couleur du mois',
      'gl': 'Cor do mes',
    },
    'g11vatw7': {
      'es': 'Color cabecera mes',
      'ca': 'Color capçalera mes',
      'en': 'Month header color',
      'eu': 'Hilabeteko goiburuaren kolorea',
      'fr': 'Couleur de l\'en-tête du mois',
      'gl': 'Cor da cabeceira do mes',
    },
    'awqdguab': {
      'es': 'Guardar',
      'ca': 'Desa',
      'en': 'Keep',
      'eu': 'Mantendu',
      'fr': 'Garder',
      'gl': 'Manteña',
    },
    'z9wf5cpu': {
      'es': 'Field is required',
      'ca': 'Field is required',
      'en': 'Field is required',
      'eu': 'Eremua beharrezkoa da',
      'fr': 'Le champ est obligatoire',
      'gl': 'O campo é obrigatorio',
    },
    '971p2n2k': {
      'es': 'Please enter a real name',
      'ca': 'Si us plau enter a real name',
      'en': 'Please enter a real name',
      'eu': 'Mesedez, idatzi benetako izena',
      'fr': 'Veuillez entrer un vrai nom',
      'gl': 'Introduce un nome real',
    },
    'izsr4m9o': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    'riv0vq8p': {
      'es': 'Please enter a short desription',
      'ca': 'Si us plau enter a short desription',
      'en': 'Please enter a short description',
      'eu': 'Mesedez, idatzi deskribapen labur bat',
      'fr': 'Veuillez saisir une brève description',
      'gl': 'Introduce unha breve descrición',
    },
    'oqw28hvx': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    '3s4lxpnl': {
      'es': 'We have to have a URL for the project.',
      'ca': 'We have to have a l\'URL per al projecte.',
      'en': 'We have to have a URL for the project.',
      'eu': 'Proiekturako URL bat izan behar dugu.',
      'fr': 'Nous devons avoir une URL pour le projet.',
      'gl': 'Temos que ter un URL para o proxecto.',
    },
    'i5kgx4lm': {
      'es': 'Please enter a valid URL...',
      'ca': 'Si us plau enter a valid URL...',
      'en': 'Please enter a valid URL...',
      'eu': 'Mesedez, sartu baliozko URL bat...',
      'fr': 'Veuillez saisir une URL valide...',
      'gl': 'Introduce un URL válido...',
    },
    'uotv4tly': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
    '17avdcnr': {
      'es': 'Field is required',
      'ca': 'Field is required',
      'en': 'Field is required',
      'eu': 'Eremua beharrezkoa da',
      'fr': 'Le champ est obligatoire',
      'gl': 'O campo é obrigatorio',
    },
    'mtfmv0d1': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
  },
  // measuresReference
  {
    'vbpb2zh1': {
      'es': 'Referencia medidas',
      'ca': 'Referència mesures',
      'en': 'Reference measures',
      'eu': 'Erreferentziako neurketak',
      'fr': 'Mesures de référence',
      'gl': 'Medidas de referencia',
    },
    '8gc6xx6r': {
      'es': 'A',
      'ca': 'A',
      'en': 'TO',
      'eu': 'ERA',
      'fr': 'À',
      'gl': 'PARA',
    },
    'xqbw7qh4': {
      'es': 'Busto',
      'ca': 'Bust',
      'en': 'Bust',
      'eu': 'Bustoa',
      'fr': 'Bousiller',
      'gl': 'Busto',
    },
    'wepniewz': {
      'es': 'B',
      'ca': 'B',
      'en': 'B',
      'eu': 'b',
      'fr': 'b',
      'gl': 'b',
    },
    'hwd32q9t': {
      'es': 'Brazo',
      'ca': 'Braç',
      'en': 'Arm',
      'eu': 'Besoa',
      'fr': 'Bras',
      'gl': 'Brazo',
    },
    'ene9q5sw': {
      'es': 'C',
      'ca': 'C',
      'en': 'C',
      'eu': 'c',
      'fr': 'c',
      'gl': 'c',
    },
    '4l63rxzg': {
      'es': 'Cintura',
      'ca': 'Cintura',
      'en': 'Waist',
      'eu': 'Gerria',
      'fr': 'Taille',
      'gl': 'Cintura',
    },
    '5aiwpl5a': {
      'es': 'D',
      'ca': 'D',
      'en': 'D',
      'eu': 'd',
      'fr': 'd',
      'gl': 'd',
    },
    'borl3ss6': {
      'es': 'Abdomen',
      'ca': 'Abdomen',
      'en': 'Abdomen',
      'eu': 'Abdomena',
      'fr': 'Abdomen',
      'gl': 'Abdome',
    },
    'd68nhnp0': {
      'es': 'E',
      'ca': 'E',
      'en': 'AND',
      'eu': 'ETA',
      'fr': 'ET',
      'gl': 'E',
    },
    'hn0w6v6y': {
      'es': 'Cadera',
      'ca': 'Maluc',
      'en': 'Hip',
      'eu': 'Aldaka',
      'fr': 'Hanche',
      'gl': 'Cadeira',
    },
    'uofli9og': {
      'es': 'F',
      'ca': 'F',
      'en': 'F',
      'eu': 'F',
      'fr': 'F',
      'gl': 'F',
    },
    '8l344peh': {
      'es': 'Muslo',
      'ca': 'Cuixa',
      'en': 'Thigh',
      'eu': 'Izterra',
      'fr': 'Cuisse',
      'gl': 'Coxa',
    },
  },
  // measuresForm
  {
    'dd6c69oi': {
      'es': 'A',
      'ca': 'A',
      'en': 'TO',
      'eu': 'ERA',
      'fr': 'À',
      'gl': 'PARA',
    },
    'v1z1vbay': {
      'es': 'Busto',
      'ca': 'Bust',
      'en': 'Bust',
      'eu': 'Bustoa',
      'fr': 'Bousiller',
      'gl': 'Busto',
    },
    'w1hatcx6': {
      'es': 'B',
      'ca': 'B',
      'en': 'B',
      'eu': 'b',
      'fr': 'b',
      'gl': 'b',
    },
    't91mr8e4': {
      'es': 'Brazo',
      'ca': 'Braç',
      'en': 'Arm',
      'eu': 'Besoa',
      'fr': 'Bras',
      'gl': 'Brazo',
    },
    'epln9v1o': {
      'es': 'C',
      'ca': 'C',
      'en': 'C',
      'eu': 'c',
      'fr': 'c',
      'gl': 'c',
    },
    '9sn783x2': {
      'es': 'Cintura',
      'ca': 'Cintura',
      'en': 'Waist',
      'eu': 'Gerria',
      'fr': 'Taille',
      'gl': 'Cintura',
    },
    '3puj3evi': {
      'es': 'D',
      'ca': 'D',
      'en': 'D',
      'eu': 'd',
      'fr': 'd',
      'gl': 'd',
    },
    'rfq3vr22': {
      'es': 'Abdomen',
      'ca': 'Abdomen',
      'en': 'Abdomen',
      'eu': 'Abdomena',
      'fr': 'Abdomen',
      'gl': 'Abdome',
    },
    'jvbf26uu': {
      'es': 'E',
      'ca': 'E',
      'en': 'AND',
      'eu': 'ETA',
      'fr': 'ET',
      'gl': 'E',
    },
    'ytbz007x': {
      'es': 'Cadera',
      'ca': 'Maluc',
      'en': 'Hip',
      'eu': 'Aldaka',
      'fr': 'Hanche',
      'gl': 'Cadeira',
    },
    'rvcyynwy': {
      'es': 'F',
      'ca': 'F',
      'en': 'F',
      'eu': 'F',
      'fr': 'F',
      'gl': 'F',
    },
    '3qhtx2zu': {
      'es': 'Muslo',
      'ca': 'Cuixa',
      'en': 'Thigh',
      'eu': 'Izterra',
      'fr': 'Cuisse',
      'gl': 'Coxa',
    },
    'z03m5786': {
      'es': 'Guardar',
      'ca': 'Desa',
      'en': 'Keep',
      'eu': 'Mantendu',
      'fr': 'Garder',
      'gl': 'Manteña',
    },
  },
  // modalAddUpdateWorkout
  {
    '447g11zi': {
      'es': 'Descripción',
      'ca': 'Descripció',
      'en': 'Description',
      'eu': 'Deskribapena',
      'fr': 'Description',
      'gl': 'Descrición',
    },
    's5flrcz3': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'jrwiogyf': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'gwkxp6vw': {
      'es': 'Duración/minutos',
      'ca': 'Durada/minuts',
      'en': 'Duration/minutes',
      'eu': 'Iraupena/minutuak',
      'fr': 'Durée/minutes',
      'gl': 'Duración/minutos',
    },
    'f2ftj8ki': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'f7s2omqi': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'bm64kqok': {
      'es': 'Valor incorrecto',
      'ca': 'Valor incorrecte',
      'en': 'Incorrect value',
      'eu': 'Balio okerra',
      'fr': 'Valeur incorrecte',
      'gl': 'Valor incorrecto',
    },
    'oo103n9f': {
      'es': 'Please choose an option from the dropdown',
      'ca': 'Si us plau choose an option from the dropdown',
      'en': 'Please choose an option from the dropdown',
      'eu': 'Mesedez, aukeratu goitibeherako aukera bat',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'gl': 'Escolle unha opción do menú despregable',
    },
  },
  // AvisoInfoDatosUsuario
  {
    'p4awklur': {
      'es': 'Ir a Perfil',
      'ca': 'Anar a Perfil',
      'en': 'Go to Profile',
      'eu': 'Joan Profilera',
      'fr': 'Aller au profil',
      'gl': 'Vai a Perfil',
    },
  },
  // Miscellaneous
  {
    '7htatabp': {
      'es': 'Esta aplicación requiere permisos de acceso a tu cámara.',
      'ca': 'Aquesta aplicació requereix permisos d\'accés a la teva càmera.',
      'en': 'This application requires access permissions to your camera.',
      'eu': 'Aplikazio honek zure kamerara sartzeko baimenak behar ditu.',
      'fr':
          'Cette application nécessite des autorisations d\'accès à votre caméra.',
      'gl': 'Esta aplicación require permisos de acceso á túa cámara.',
    },
    '7sjne31a': {
      'es':
          'Esta aplicación requiere permisos de acceso a tu librería de fotos.',
      'ca':
          'Aquesta aplicació requereix permisos d\'accés a la teva llibreria de fotos.',
      'en':
          'This application requires access permissions to your photo library.',
      'eu':
          'Aplikazio honek zure argazki liburutegirako sarbide-baimenak behar ditu.',
      'fr':
          'Cette application nécessite des autorisations d\'accès à votre photothèque.',
      'gl':
          'Esta aplicación require permisos de acceso á túa biblioteca de fotos.',
    },
    'c7szw8jw': {
      'es': 'Esta aplicación requiere permisos de acceso a notificaciones.',
      'ca': 'Aquesta aplicació requereix permisos daccés a notificacions.',
      'en': 'This app requires notification access permissions.',
      'eu': 'Aplikazio honek jakinarazpenak atzitzeko baimenak behar ditu.',
      'fr':
          'Cette application nécessite des autorisations d\'accès aux notifications.',
      'gl': 'Esta aplicación require permisos de acceso ás notificacións.',
    },
    '7wc231cg': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'ctcyp44k': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'le2wyxub': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    '33rvpmvy': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'pzo8mkfd': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'c0e1z4rk': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    '4eyquknk': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    '9meop0sv': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'y1jxt5b4': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    '936giw7y': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'ipprrnp5': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'lu6virmv': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    '8rp5hwzs': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'h5mxh63n': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'jl1hbnhg': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'pbped2i7': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'a8rqgla1': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'k6nrrhq6': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    '970c7amc': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'ot8zcu06': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'hwm8ztpw': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'y2hutue8': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'sgqxt0ui': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'sjgkkzzo': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
    'jr76p7cy': {
      'es': '',
      'ca': '',
      'en': '',
      'eu': '',
      'fr': '',
      'gl': '',
    },
  },
].reduce((a, b) => a..addAll(b));
